---
version: '3.2'

networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay

services:
  master:
    build: .
    image: ahstn/jenkins-casc:1.0.0-alpha
    ports:
      - 8080:8080   # Expose web ui
      - 50000:50000 # Expose agent port
      - 433         # Allow outgoing https connections for Jenkins Plugins
    environment:
      DOCKER_HOST: tcp://172.17.0.1:2376
    networks:
      - frontend

  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.5.0
    ports:          # Might be better as 'expose' instead of 'ports'
      - 9090:9090   # Expose metrics and web ui
      - 8080        # Allow outgoing connection to Jenkins
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - jenkins
    networks:
      - frontend

  loki:
    image: grafana/loki:master
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - backend

  promtail:
    image: grafana/promtail:master
    volumes:
      - /var/log:/var/log
    command:
      -config.file=/etc/promtail/docker-config.yaml
    networks:
      - backend

  # 'master' tag requred for loki compatibility and explore feature
  # http://docs.grafana.org/features/explore/#turning-the-explore-feature-on
  grafana:
    image: grafana/grafana:master
    environment:
      GF_SECURITY_ADMIN_USER: ${ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_EXPLORE_ENABLED: 'true'
    ports:
      - 3000:3000   # Expose web ui
      - 9090        # Allow outoging connecion to Prometheus
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning:ro
    networks:
      - backend
      - frontend
